### ISSUE TITLE
5.5.1 mercurial version is not supported

### ISSUE THREAD

**Issue by denix666** [cicd-team/mercurial-reviewboard#1]
Hello,

When using 5.5.1 mercurial version get next error:
`*** failed to import extension reviewboard from /path/to/plugin: No module named 'mercurial_reviewboard'`

**Comment by svilkelis** [comment]
This is due to python3 and needs to rewrite whole plugin completely..

**Comment by denix666** [comment]
Issue fixed in branch "python3"
